# Generated by Django 3.2 on 2021-12-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresholds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='request_threshold',
            field=models.IntegerField(unique=True),
        ),
    ]
